name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        **PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.
        
        Is this a client library issue or a product issue? We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [Support page](https://cloud.google.com/support) to reach the most relevant engineers.

  - type: input
    id: programming-language
    attributes:
      label: Programming Language
      description: What programming language are you using?
      placeholder: "e.g., Python, Java, Node.js, Go"
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: runtime-version
    attributes:
      label: Language Runtime Version
      description: What version of the language runtime are you using?
      placeholder: "e.g., Python 3.11.5, Node.js 18.17.0, Java 17"
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: What version of the package are you using?
      placeholder: "e.g., 1.2.3"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Please provide a clear and concise description of the bug
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output or error messages
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, code snippets, etc.)
    validations:
      required: false
