name: Question
description: Ask a question
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for stopping by to ask us a question!
        
        **PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

  - type: textarea
    id: goal
    attributes:
      label: What are you trying to do?
      description: Please describe what you're trying to accomplish
    validations:
      required: true

  - type: textarea
    id: code-tried
    attributes:
      label: What have you tried?
      description: Please share any code you've already tried
      render: shell
    validations:
      required: false

  - type: textarea
    id: error-messages
    attributes:
      label: Error messages
      description: Please paste any error messages you're getting
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the question here
    validations:
      required: false
